name: Publish

on:
  workflow_run:
    workflows: [ Release ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # there is no deps so no installation

      - name: Build distribution package
        run: poetry build

      - uses: actions/upload-artifact@v4
        with:
          name: package-dist
          path: dist
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/yapee/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
