name: Release

on:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # it would be nice to be able to generate changelogs there

      - name: Create & publish release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
